export const dummyUser = [
  // { userid: 'aaa1', usernickname: '김준기', useremail: '김준기@naver.com', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 101, userselfintroduction: '김준기자기소개'},
  // { userid: 'aa1', usernickname: '신중현', useremail: '신중현@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 2, postCount: 102, userselfintroduction: '신중현자기소개' },
  // { userid: 'aa2', usernickname: '전성모', useremail: '전성모@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 3, postCount: 103,userselfintroduction: '전성모자기소개' },
  // { userid: 'aa3', usernickname: '이규훈', useremail: '이규훈@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 4, postCount: 104,userselfintroduction: '이규훈자기소개' },
  // { userid: 'aa4', usernickname: '김지영', useremail: '김지영@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 5, postCount: 105,userselfintroduction: '김지영자기소개' },
  // { userid: 'aa5', usernickname: '정영훈', useremail: '정영훈@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 6, postCount: 106,userselfintroduction: '정영훈자기소개' },
  // { userid: 'aa6', usernickname: '임윤서', useremail: '임윤서@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 7, postCount: 107,userselfintroduction: '임윤서자기소개' },
  // { userid: 'aa7', usernickname: '홍희범', useremail: '홍희범@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 8, postCount: 108,userselfintroduction: '홍희범자기소개' },
  // { userid: 'aa8', usernickname: '이해창', useremail: '이해창@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 9, postCount: 109,serselfintroduction: '이해창자기소개'},      
  // { userid: 'aa9', usernickname: '임성훈', useremail: '임성훈@naver.com', imageUrl: 'https://picsum.photos/200', likesCount: 10, postCount: 110,userselfintroduction: '임성훈자기소개'},
  // { userid: 'aaa2', usernickname: '김상백', useremail: '김상백@naver.com', imageUrl: 'https://picsum.photos/200' , likesCount: 11, postCount: 111,userselfintroduction: '김상백자기소개'},
  // { userid: 'aaa3', usernickname: '문영현', useremail: '문영현@naver.com', imageUrl: 'https://picsum.photos/200' , likesCount: 12, postCount: 112,userselfintroduction: '문영현자기소개'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '1', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 12223333, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '2', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '3', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '4', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '5', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '6', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '7', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '8', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '9', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '10', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '11', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '12', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '13', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '14', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '15', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '16', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '17', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '18', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '19', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '20', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '21', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '22', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '23', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '24', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '25', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '26', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '27', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '28', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
  { userid: 'aaa1', usernickname: '김준기', useremail: '29', imageUrl: 'https://picsum.photos/200' , likesCount: 1, postCount: 1, userselfintroduction: '1'},
];